### ISSUE TITLE
[Up for consideration] use chromium for rendering UI

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/Rizumu#11]
https://github.com/cefsharp/CefSharp

idea by SSG / uwx

**Comment by Emzi0767** [comment]
Drawbacks:
- Severe reduction of portability.
- Drastic increase in application size.
- Having to bundle natives for several platforms.
- Severe increase in resource usage.

Advantages:
- ???

**Comment by uwx** [comment]
This is Rizumu not D#+. It's a video game. And you can build the UI in HTML in CSS instead of hardcoding values.

**Comment by Emzi0767** [comment]
All points apply to CEF specifically. This would also effectively prevent making Android (etc) version without putting significant effort into it.

CEF is not a light framework, it's very resource-intensive. Furthermore, it's not 100% managed code. Large majority of CEF and its components (most notably V8) are native code, and might not run everywhere.

**Comment by uwx** [comment]
If Rizumu was still cross-platform, then I'd understand your concern, but as far as I know Android support has been all but completely abandoned.

**Comment by Emzi0767** [comment]
What about Linux? Mac? Other UNIXes? People use those.

**Comment by uwx** [comment]
¯\\\_(ツ)_/¯

**Comment by Naamloos** [comment]
I dropped support out of laziness. Idk.

**Comment by Naamloos** [comment]
dropping idea
