### ISSUE TITLE
HLSL Shaders (monogame / xna)

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/Rizumu#5]
The game looks a bit dull. Monogame has support for HLSL shaders, though I don't know any HLSL. If anyone knows HLSL and is willing to help me out, I'd appreciate it! :)

**Comment by Naamloos** [comment]
e.g. motion blur on notes, splash effect on notes when hit?

**Comment by Maybeking** [comment]
Hello, here is a quick tutorial to create shader in XNA/MonoGame, feel free to take a look : [http://rbwhitaker.wikidot.com/first-shader](http://rbwhitaker.wikidot.com/first-shader)

**Comment by Naamloos** [comment]
Closing for now. Will reopen when I'm desperate for visual effects again.
